### ISSUE TITLE
Error when executing generator.py list index out of range

### ISSUE THREAD

**Issue by mnegretev** [johaq/CompetitionTemplate#1]
I followed the instructions for installing the command generator (https://github.com/johaq/CommandGenerator) and generating the object.md, but when running the generator.py, I got the following error:

Traceback (most recent call last):
  File "generator.py", line 93, in <module>
    object_names, object_categories_plural, object_categories_singular = parse_objects(objects_data)
  File "generator.py", line 67, in parse_objects
    parsed_categories_singular = [category[1] for category in parsed_categories]
  File "generator.py", line 67, in <listcomp>
    parsed_categories_singular = [category[1] for category in parsed_categories]
IndexError: list index out of range

**Comment by ARTenshi** [comment]
Same problem here; I think it's an issue with the "generate_object_list.py". A workaround is manually editing all the Class headers in object.md from "# Class name" to "# Class name (name_singular)"). e.g. "# Class dishes" to "# Class dishes (dish)".
